### ISSUE TITLE
convertToAbsoluteUrls makes the URL prefix prepended to SVG data URLs if they contain comments

### ISSUE THREAD

**Issue by mgol** [webpack-contrib/style-loader#214]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
Data URLs defining SVGs with HTML comments get a URL prefix prepended, breaking the rule.

**If the current behavior is a bug, please provide the steps to reproduce.**

For the following input:
```css
.test {
    background-image: url('data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%0A%3C!--%20Comment)%20--%3E%0A%3Csvg%3E%3C%2Fsvg%3E%0A');
}
```
Using the `style-loader` with the default `convertToAbsoluteUrls: true` and source maps enabled gets converted to:
```css
.test {
  background-image: url("https://localhost:8000/my-current-path/'data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%0A%3C!--%20Comment")%20--%3E%0A%3Csvg%3E%3C%2Fsvg%3E%0A');
}
```
Let me know if that's not enough to reproduce on your end.

**What is the expected behavior?**
Nothing should get prepended.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
macOS 10.12.4 (16E195), Node.js 6.10.2, Webpack 2.3.3, style-loader 0.16.1

Related: #195
