### ISSUE TITLE
The browser can't found -webkit-box-orient at extract mod

### ISSUE THREAD

**Issue by thomasyxy** [webpack-contrib/style-loader#305]
It will happen when I open extract.

## my code:

``` css
.clamp-2 {
  overflow : hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.clamp-1 {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```

## result:

``` css
.clamp-2 {
    display: -webkit-box;
    -webkit-line-clamp: 2
}

.clamp-1,.clamp-2 {
    overflow: hidden;
    text-overflow: ellipsis
}

.clamp-1 {
    white-space: nowrap
}
```

webpack: 3.10.0
style-loader: 0.19.1
