### ISSUE TITLE
/url using css payload as href

### ISSUE THREAD

**Issue by brewster1134** [webpack-contrib/style-loader#343]
when trying to use the url style loader, the contents of the css file gets used as the href value

`<link rel="stylesheet" type="text/css" href="body{&#10;  background: red; }&#10;">`

my configuration is pretty basic...

```css
...
    module: {
      rules: [{
          test: /\.css/,
          use: [
            { loader: 'style-loader/url' },
            { loader: 'css-loader' }
          ]
...
```

adding a break to the code, the `url` arguments that gets passed to `addStyleUrl` is actually an array instead of what should be a string

```javascript
[
  "./node_modules/css-loader/index.js!./server/styles/app.css",
  "body { background: red; }",
  ""
]
```
