### ISSUE TITLE
URL replacement hangs on bad CSS urls

### ISSUE THREAD

**Issue by Alxandr** [webpack-contrib/style-loader#365]
**Do you want to request a *feature* or report a *bug*?** 

improvement

**What is the current behavior?**
If you have a particulary bad `url` expression, generally due to misconfigured webpack loaders, `css.replace` hangs indefinitely with 100% CPU usage (latest chrome on windows).

**If the current behavior is a bug, please provide the steps to reproduce.**

I had a bug in my loader setup that produced the following CSS output:

```css
@font-face {
    font-family: 'edit-insurance-spa-icons';
    src: url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.73a3d26c.eot);
    src: url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.73a3d26c.eot#iefix) format("embedded-opentype"), 
        url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.440ed78a.ttf) format("truetype"), 
        url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.8d94d9ba.woff) format("woff"), 
        url("function EditInsuranceSpaIcons (props) {\n    return React.createElement(\"svg\",props,[React.createElement(\"metadata\",{\"key\":0},React.createElement(\"json\",null,\"\r\n\r\n{\r\n\t\\"fontFamily\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"majorVersion\\": 1,\r\n\t\\"minorVersion\\": 1,\r\n\t\\"version\\": \\"Version 1.1\\",\r\n\t\\"fontId\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"psName\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"subFamily\\": \\"Regular\\",\r\n\t\\"fullName\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"description\\": \\"Font generated by IcoMoon.\\"\r\n}\r\n\r\n\")),React.createElement(\"defs\",{\"key\":1},React.createElement(\"font\",{\"id\":\"edit-insurance-spa-icons\",\"horizAdvX\":\"1024\"},[React.createElement(\"font-face\",{\"unitsPerEm\":\"1024\",\"ascent\":\"960\",\"descent\":\"-64\",\"key\":0}),React.createElement(\"missing-glyph\",{\"horizAdvX\":\"1024\",\"key\":1}),React.createElement(\"glyph\",{\"unicode\":\" \",\"horizAdvX\":\"0\",\"d\":\"\",\"key\":2}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"if-logo\",\"data-tags\":\"if-logo\",\"horizAdvX\":\"1044\",\"d\":\"M522.020 962.208c-288.328 0-522.020-230.22-522.020-514.21 0-284.030 233.692-514.226 522.020-514.226 288.306 0 522.042 230.16 522.042 514.228 0.018 283.99-233.734 514.208-522.042 514.208zM391.126 775.054c18.553 0 39.393-11.725 37.545-41.943-0.762-12.348-8.475-47.586-47.344-47.586-22.811 0-38.611 14.838-37.045 40.801 1.666 26.502 20.881 48.107 46.844 48.729zM214.394 326.904c0 16.184 6.932 35.24 21.707 71.18l42.346 107.158c4.236 11.264 13.453 33.109 13.453 42.285 0 2.832-1.705 8.053-5.238 8.053-2.449 0-6.666-2.75-9.316-4.758-9.879-7.229-36.965-36.664-36.965-36.664-2.148-2.369-5.623-2.248-7.592-0.482l-10.34 9.857c-3.375 3.271-2.248 6.406-0.643 8.313 22.789 25.84 81.76 90.053 136.713 90.053 11.986 0 28.572-5.34 28.572-27.166 0-16.906-10.1-42.445-18.592-62.182l-40.859-98.605-16.906-44.373c-2.088-5.621-6.123-17.527-6.123-24.014 0-1.225-0.18-8.715 5.943-8.715 13.512 0 53.229 44.191 53.229 44.191 2.67 2.73 6.043 2.088 7.85 0.342l10.963-10.48c1.785-1.646 3.252-4.881 0.361-8.174 0 0-74.211-88.586-133.021-88.586-25.301 0-35.541 14.438-35.541 32.768zM640.964 299.56c-21.404 0-36.48 13.91-35.396 38.246 1.084 24.879 18.795 45.178 43.168 45.76 17.328 0 37.146-11.002 35.92-39.373-0.543-11.604-7.189-44.633-43.691-44.633zM716.14 765.074c-6.686 14.777-11.18 23.973-27.223 23.832-9.156-0.119-19.174-8.713-22.688-12.246-40.197-40.197-61.379-113.121-75.473-162.473h59.090c3.613 0 4.898-3.031 4.074-5.48l-7.43-21.324c-0.863-2.391-2.912-5.643-7.57-5.643l-57.203 1.023-54.613-232.77c-22.328-85.855-46.199-146.834-89.188-195.465-33.812-38.732-84.008-63.449-122.82-63.449-19.676 0-78.586 7.869-78.586 43.168 0 26.062 26.102 47.686 45.115 47.686 18.352 0 26.584-17.367 29.434-30.098 4.236-17.588 11.926-28.25 26.703-28.25 10.602 0 21.041 6.084 36.662 25.779 17.428 21.945 41.924 83.967 57.104 144.846 12.107 48.51 71.898 288.166 71.898 288.166l-44.414-0.582c-3.271 0-4.697 2.992-4.035 5.34l6.766 22.891c0.682 2.168 3.232 4.777 6.244 4.777l44.494-0.602c13.352 45.115 33.33 110.492 76.881 154.744 30.277 30.318 71.961 48.932 115.631 48.932 37.064 0 83.527-17.287 83.527-44.111 0-19.695-19.236-48.287-44.795-48.287-22.125-0.018-21.041 25-27.586 39.596zM768.208 299.556c-21.404 0-36.504 13.91-35.4 38.246 1.064 24.879 18.775 45.178 43.15 45.76 17.328 0 37.166-11.002 35.92-39.373-0.52-11.604-7.166-44.633-43.67-44.633zM895.402 299.552c-21.363 0-36.461 13.91-35.377 38.246 1.084 24.879 18.795 45.178 43.168 45.76 17.328 0 37.166-11.002 35.92-39.373-0.482-11.604-7.168-44.633-43.711-44.633z\",\"key\":3}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"account\",\"data-tags\":\"account\",\"d\":\"M512 789.333c94.257 0 170.667-76.41 170.667-170.667v0c0-94.257-76.41-170.667-170.667-170.667v0c-94.257 0-170.667 76.41-170.667 170.667v0c0 94.257 76.41 170.667 170.667 170.667v0zM512 362.667c188.587 0 341.333-76.373 341.333-170.667v-85.333h-682.667v85.333c0 94.293 152.747 170.667 341.333 170.667z\",\"key\":4}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"headset\",\"data-tags\":\"headset\",\"d\":\"M512 917.333c-213.333 0-384-170.667-384-384v-298.667c0-70.692 57.308-128 128-128v0h128v341.333h-170.667v85.333c0 164.949 133.718 298.667 298.667 298.667v0c164.949 0 298.667-133.718 298.667-298.667v0-85.333h-170.667v-341.333h170.667v-42.667h-298.667v-85.333h256c70.692 0 128 57.308 128 128v0 426.667c0 213.333-171.947 384-384 384z\",\"key\":5}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"sad\",\"data-tags\":\"sad\",\"d\":\"M512-64c282.77 0 512 229.23 512 512s-229.23 512-512 512-512-229.23-512-512 229.23-512 512-512zM512 864c229.75 0 416-186.25 416-416s-186.25-416-416-416-416 186.25-416 416 186.25 416 416 416zM256 640c0 35.346 28.654 64 64 64s64-28.654 64-64c0-35.346-28.654-64-64-64s-64 28.654-64 64zM640 640c0 35.346 28.654 64 64 64s64-28.654 64-64c0-35.346-28.654-64-64-64s-64 28.654-64 64zM319.902 179.26l-82.328 49.396c55.962 93.070 157.916 155.344 274.426 155.344 116.508 0 218.462-62.274 274.426-155.344l-82.328-49.396c-39.174 65.148-110.542 108.74-192.098 108.74-81.558 0-152.924-43.592-192.098-108.74z\",\"key\":6}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"check-heavy\",\"data-tags\":\"check-heavy\",\"d\":\"M864 832l-480-480-224 224-160-160 384-384 640 640z\",\"key\":7})]))]);\n}#edit-insurance-spa-icons") format("svg");
    font-weight: normal;
    font-style: normal;
}
```

This causes the browser to just spinn and hang. Pausing the JS showed the the issue was the regex replace expression, and trying to run that expression in the devtools produced the same effect.

**What is the expected behavior?**
While wrong in functionality, as far as I can tell, the above CSS is perfectly valid CSS. I would expect to either get an error (probably from the browser itself), or it just silently failing. The issue with the browser just hanging is that it's very tricky to figure out what the issue is, and what's causing it.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Less frustration trying to figure out what's wrong.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack: 4.28.4
node: 11.6.0
style-loader: 0.23.1
windows 10

**Comment by evilebottnawi** [comment]
@Alxandr what is version of `css-loader` you use? Can you create minimum reproducible test repo?

**Comment by Alxandr** [comment]
**webpack.config.js**:
```js
const path = require("path");

module.exports = {
  mode: "development",

  entry: {
    main: path.resolve(__dirname, "index.js")
  },

  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              url: false,
              sourceMap: true // code path not triggered if there is no source maps
            }
          }
        ]
      }
    ]
  }
};
```

**index.js**:
```js
import './index.css';
```

**index.css**:
```css
@font-face {
  font-family: 'edit-insurance-spa-icons';
  src: url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.73a3d26c.eot);
  src: url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.73a3d26c.eot#iefix) format("embedded-opentype"), 
      url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.440ed78a.ttf) format("truetype"), 
      url(/app/dist/static/gen-1/media/edit-insurance-spa-icons.8d94d9ba.woff) format("woff"), 
      url("function EditInsuranceSpaIcons (props) {\n    return React.createElement(\"svg\",props,[React.createElement(\"metadata\",{\"key\":0},React.createElement(\"json\",null,\"\r\n\r\n{\r\n\t\\"fontFamily\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"majorVersion\\": 1,\r\n\t\\"minorVersion\\": 1,\r\n\t\\"version\\": \\"Version 1.1\\",\r\n\t\\"fontId\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"psName\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"subFamily\\": \\"Regular\\",\r\n\t\\"fullName\\": \\"edit-insurance-spa-icons\\",\r\n\t\\"description\\": \\"Font generated by IcoMoon.\\"\r\n}\r\n\r\n\")),React.createElement(\"defs\",{\"key\":1},React.createElement(\"font\",{\"id\":\"edit-insurance-spa-icons\",\"horizAdvX\":\"1024\"},[React.createElement(\"font-face\",{\"unitsPerEm\":\"1024\",\"ascent\":\"960\",\"descent\":\"-64\",\"key\":0}),React.createElement(\"missing-glyph\",{\"horizAdvX\":\"1024\",\"key\":1}),React.createElement(\"glyph\",{\"unicode\":\" \",\"horizAdvX\":\"0\",\"d\":\"\",\"key\":2}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"if-logo\",\"data-tags\":\"if-logo\",\"horizAdvX\":\"1044\",\"d\":\"M522.020 962.208c-288.328 0-522.020-230.22-522.020-514.21 0-284.030 233.692-514.226 522.020-514.226 288.306 0 522.042 230.16 522.042 514.228 0.018 283.99-233.734 514.208-522.042 514.208zM391.126 775.054c18.553 0 39.393-11.725 37.545-41.943-0.762-12.348-8.475-47.586-47.344-47.586-22.811 0-38.611 14.838-37.045 40.801 1.666 26.502 20.881 48.107 46.844 48.729zM214.394 326.904c0 16.184 6.932 35.24 21.707 71.18l42.346 107.158c4.236 11.264 13.453 33.109 13.453 42.285 0 2.832-1.705 8.053-5.238 8.053-2.449 0-6.666-2.75-9.316-4.758-9.879-7.229-36.965-36.664-36.965-36.664-2.148-2.369-5.623-2.248-7.592-0.482l-10.34 9.857c-3.375 3.271-2.248 6.406-0.643 8.313 22.789 25.84 81.76 90.053 136.713 90.053 11.986 0 28.572-5.34 28.572-27.166 0-16.906-10.1-42.445-18.592-62.182l-40.859-98.605-16.906-44.373c-2.088-5.621-6.123-17.527-6.123-24.014 0-1.225-0.18-8.715 5.943-8.715 13.512 0 53.229 44.191 53.229 44.191 2.67 2.73 6.043 2.088 7.85 0.342l10.963-10.48c1.785-1.646 3.252-4.881 0.361-8.174 0 0-74.211-88.586-133.021-88.586-25.301 0-35.541 14.438-35.541 32.768zM640.964 299.56c-21.404 0-36.48 13.91-35.396 38.246 1.084 24.879 18.795 45.178 43.168 45.76 17.328 0 37.146-11.002 35.92-39.373-0.543-11.604-7.189-44.633-43.691-44.633zM716.14 765.074c-6.686 14.777-11.18 23.973-27.223 23.832-9.156-0.119-19.174-8.713-22.688-12.246-40.197-40.197-61.379-113.121-75.473-162.473h59.090c3.613 0 4.898-3.031 4.074-5.48l-7.43-21.324c-0.863-2.391-2.912-5.643-7.57-5.643l-57.203 1.023-54.613-232.77c-22.328-85.855-46.199-146.834-89.188-195.465-33.812-38.732-84.008-63.449-122.82-63.449-19.676 0-78.586 7.869-78.586 43.168 0 26.062 26.102 47.686 45.115 47.686 18.352 0 26.584-17.367 29.434-30.098 4.236-17.588 11.926-28.25 26.703-28.25 10.602 0 21.041 6.084 36.662 25.779 17.428 21.945 41.924 83.967 57.104 144.846 12.107 48.51 71.898 288.166 71.898 288.166l-44.414-0.582c-3.271 0-4.697 2.992-4.035 5.34l6.766 22.891c0.682 2.168 3.232 4.777 6.244 4.777l44.494-0.602c13.352 45.115 33.33 110.492 76.881 154.744 30.277 30.318 71.961 48.932 115.631 48.932 37.064 0 83.527-17.287 83.527-44.111 0-19.695-19.236-48.287-44.795-48.287-22.125-0.018-21.041 25-27.586 39.596zM768.208 299.556c-21.404 0-36.504 13.91-35.4 38.246 1.064 24.879 18.775 45.178 43.15 45.76 17.328 0 37.166-11.002 35.92-39.373-0.52-11.604-7.166-44.633-43.67-44.633zM895.402 299.552c-21.363 0-36.461 13.91-35.377 38.246 1.084 24.879 18.795 45.178 43.168 45.76 17.328 0 37.166-11.002 35.92-39.373-0.482-11.604-7.168-44.633-43.711-44.633z\",\"key\":3}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"account\",\"data-tags\":\"account\",\"d\":\"M512 789.333c94.257 0 170.667-76.41 170.667-170.667v0c0-94.257-76.41-170.667-170.667-170.667v0c-94.257 0-170.667 76.41-170.667 170.667v0c0 94.257 76.41 170.667 170.667 170.667v0zM512 362.667c188.587 0 341.333-76.373 341.333-170.667v-85.333h-682.667v85.333c0 94.293 152.747 170.667 341.333 170.667z\",\"key\":4}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"headset\",\"data-tags\":\"headset\",\"d\":\"M512 917.333c-213.333 0-384-170.667-384-384v-298.667c0-70.692 57.308-128 128-128v0h128v341.333h-170.667v85.333c0 164.949 133.718 298.667 298.667 298.667v0c164.949 0 298.667-133.718 298.667-298.667v0-85.333h-170.667v-341.333h170.667v-42.667h-298.667v-85.333h256c70.692 0 128 57.308 128 128v0 426.667c0 213.333-171.947 384-384 384z\",\"key\":5}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"sad\",\"data-tags\":\"sad\",\"d\":\"M512-64c282.77 0 512 229.23 512 512s-229.23 512-512 512-512-229.23-512-512 229.23-512 512-512zM512 864c229.75 0 416-186.25 416-416s-186.25-416-416-416-416 186.25-416 416 186.25 416 416 416zM256 640c0 35.346 28.654 64 64 64s64-28.654 64-64c0-35.346-28.654-64-64-64s-64 28.654-64 64zM640 640c0 35.346 28.654 64 64 64s64-28.654 64-64c0-35.346-28.654-64-64-64s-64 28.654-64 64zM319.902 179.26l-82.328 49.396c55.962 93.070 157.916 155.344 274.426 155.344 116.508 0 218.462-62.274 274.426-155.344l-82.328-49.396c-39.174 65.148-110.542 108.74-192.098 108.74-81.558 0-152.924-43.592-192.098-108.74z\",\"key\":6}),React.createElement(\"glyph\",{\"unicode\":\"\",\"glyphName\":\"check-heavy\",\"data-tags\":\"check-heavy\",\"d\":\"M864 832l-480-480-224 224-160-160 384-384 640 640z\",\"key\":7})]))]);\n}#edit-insurance-spa-icons") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

**index.html**:
```html
<!DOCTYPE html>
<html>
  <head>
    <script async defer src="/main.js"></script>
  </head>
  <body></body>
</html>
```

**package.json**:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "css-loader": "^2.1.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.0",
    "webpack-dev-server": "^3.1.14"
  }
}
```

I ran `npx webpack-dev-server --hot` and navigated to `localhost:8080`. Not sure whether or not the `--hot` is required.
